## Week 2 MA544
---
**Agenda**
1. Revise Eigenvalues and Eigenvectors
1. Norms of Vectors and Matrices
1. Special Matrices 
1. Finite Precision Mathematics on a Computer

In [2]:
#IMPORT
import numpy as np
import matplotlib.pyplot as plt
import matplotlib.image as mpimg
%matplotlib inline

#from ipywidgets import interact, interactive, fixed, interact_manual
#import ipywidgets as widgets

## Set a seed for the random number generator
np.random.seed(100)

### Eigenvalues and eigenvectors
<hr>

An eigenvector of a square matrix $A$ is a special non-zero vector such that
$$ A v  = \lambda v$$
where $\lambda$ is called the associated eigenvalue.

**Example**: Find the eigenvalues and eigenvectors of 
$
A = \left( \begin{array}{cc} 2 & 4  \\
1 & -1 
\end{array}
\right) 
$
##### Discussion about solving characteristic polynomials.
**Example** Find the eigenvalues of the matrix $B = f(A)$ where $f(x) = x^2-3x +5$.


---
### Eigen-decomposition

If the square matrix $A\in \mathbb{C}^{n\times n}$ has $n$ linearly independent eigenvectors  then $A$ can be given in the following factorized form as
$$
A = Q \Lambda Q^{-1},
$$
where $\Lambda = $ diag$(\lambda_1, \cdots, \lambda_n)$ and columns of matrix $Q$ are made of the eigenvector $q_i$ of $A$ $(i=1,\cdots,n)$, arranged in the same order as the eigenvalues in $\Lambda$.
>- When $A$ is a real and symmetric matrix: $A = Q \Lambda Q^T$, where $Q$ is orthogonal $(Q^TQ = I = QQ^T)$ and $\Lambda$ is made of real diagonal entries.
>- If a function $f(x)$ has power series expansion in $x$, then $f(A) = Q f(\Lambda) Q^{-1}$.

#### Discussion on Spectral Decomposition and Projection



### Invertibility: A discussion
---
Please go to POLL EVERYWHERE for a quiz to visit the properties of inverses.

In [5]:
## This setting restricts the dispaly of decimals to simpler forms
np.set_printoptions(formatter={'float': lambda x: "{0:10.5f}".format(x)})

## Generate matrix of randoem integers for experiment
A = np.random.randint(0,9, size=(4,4))

##Finding inverse of a square matrix.
invA = np.linalg.inv(A) 

print(" Matrix A:\n",A,"\n\n Inverse if A:\n", invA)

print ("Verify inverse:\n",np.dot(A,invA))

 Matrix A:
 [[2 3 2 5]
 [8 1 0 7]
 [6 2 0 8]
 [2 5 1 8]] 

 Inverse if A:
 [[  -0.10714    0.60714   -0.67857    0.21429]
 [  -0.39286    0.89286   -1.32143    0.78571]
 [   0.75000   -0.25000    0.25000   -0.50000]
 [   0.17857   -0.67857    0.96429   -0.35714]]
Verify inverse:
 [[   1.00000   -0.00000    0.00000    0.00000]
 [   0.00000    1.00000    0.00000   -0.00000]
 [   0.00000    0.00000    1.00000    0.00000]
 [   0.00000   -0.00000    0.00000    1.00000]]


### Vector and Matrix Norms
---
Continued on the whiteboard and worksheet.

#### Manhattan distance (Taxi-cab distnace)
<div style="width:500px">
<img src="./images/Manhattan_distance.png" width=50%/>
</div>

[Image Source](https://en.wikipedia.org/wiki/Taxicab_geometry#/media/File:Manhattan_distance.svg)


In general, a norm is any function that assigns a real number to any vector, $\|\cdot\|: V \to \mathbb{R}$, and that satisfies the following properties
  
>1. Nonnegativity: $\|\bf{v}\| \geq 0$.
>1. Definiteness:  $\|\bf{v}\| = 0 \Leftrightarrow \bf{v}=0$.
>1. Homegeneity: For any real number $\alpha$,  $\|\alpha \bf{v}\| = |\alpha| \|\bf{v}\|$.
>1. Triangle law: $\|\bf{u} + \bf{v}\| \leq \|\bf{u}\| + \|\bf{v}\|$.
  
  EXAMPLES 
  
>- $l_1$ norm
<img src="./images/NormL1.png" width=60%/>

>- $l_2$ norm
<img src="./images/NormL2.png" width=60%/>

>- $l_{p}$ norm
<img src="./images/NormLp.png" width=60%/>

>- $l_{\infty}$ norm
$$ \|x\|_{\infty} = \max_{i=1,\cdots,n} |x_i|$$

**Example** Determine if the expression  defines a norm on $\mathbb{R}^n$: 
$$
f({\bf x}) = \sum\limits_{i=1}^n |x_i|^3.
$$

#### Unit circles in $\mathbb{R}^2$:  $\|x\|_1 \leq 1$ and $\|x\|_2 \leq 1$
<img src="https://upload.wikimedia.org/wikipedia/commons/f/f8/L1_and_L2_balls.svg" width="80%" />

[Image Source: WikiMedia](https://upload.wikimedia.org/wikipedia/commons/f/f8/L1_and_L2_balls.svg)

### Matrix norms 
Matrix norms could be defined as an extension of vector norms by considering matrices as $mn$-dimensional vectors.
#### Frobenius Norms
$$
\|A\|_F = \left( \sum\limits_{i=1}^m \sum\limits_{j=1}^n a_{i,j}^2 \right)^{1/2}.
$$

**Example**: Verify that $\|A\|_F = \sqrt{\operatorname{tr}(A^T A) }$.




##### Matrix Norm Induced by a Vector Norm
$$
\| A\| = \textrm{sup} \left\{   \|Au\|: u \in \mathbb{R}^n, \|u\| = 1 \right\}
$$

 An important consequence is that the subordinate norm also satisfies
$$
\|A x\| \leq \|A\| \|x\|
$$
$$
\|A B\| \leq \|A\| \|B\|
$$
$$
\|I\| = 1
$$
EXAMPLES

>- The subordinate matrix norm induced by  $\|\cdot\|_{\infty}$, called max-row-sum norm, is given by
$$
\|A\|_{\infty} = \textrm{max}_{1 \leq i \leq n} \sum\limits_{j=1}^{n} |a_{ij}|
$$

>- The subordinate matrix norm induced by  $\|\cdot\|_{1}$, called max-column-sum norm, is given by
$$
\|A\|_{1} = \textrm{max}_{1 \leq j \leq n} \sum\limits_{i=1}^{n} |a_{ij}|
$$

>- The subordinate matrix norm induced by  $\|\cdot\|_{2}$, called spectral norm, is given by
$$
\|A\|_{2} = \sqrt{\rho(A^T A)}
$$

In [8]:
# NORM : Euclidean, Frobenius

D1 = np.array([[1,1],[1,-1]])
print ("D1 and its norm: \n", D1)
print (np.linalg.norm(D1))

D2 = np.array([[1,2, -1],[3,4, -6]])
print ("D1 and its norm: \n", D2)
print (np.linalg.norm(D2))

np.linalg.norm

#print np.linalg.norm(D2, ord=np.inf)

D1 and its norm: 
 [[ 1  1]
 [ 1 -1]]
2.0
D1 and its norm: 
 [[ 1  2 -1]
 [ 3  4 -6]]
8.18535277187245


### Some Special Matrices
***
- Symmetric ans Skew-symmetric Matrics
- Upper and Lower Triangular Matrices
- Banded Matrices
- Orthogonal and Unitary Matrices
- Positive definite, positive semidefinite matrices
- Negative definite, negative semidefinite matrices
- Indefinite Matrices
- Permutation Matrix
- Diagonally Dominant Matrices
- Nonnegative Matrices